---
name: wm_state_properties_lint
description: A starting point for Dart libraries or applications.
version: 1.1.0
# repository: https://github.com/my_org/my_repo
resolution: workspace

environment:
  sdk: '>=3.11.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  analysis_server_plugin: ^0.3.7
  analyzer: ^10.0.1
  analyzer_plugin: ^0.14.1

dev_dependencies:
  analyzer_testing: ^0.1.9
  injectable_generator: ^2.8.1
  lints: ^6.1.0
  test: ^1.24.0
  test_reflective_loader: ^0.4.0
